name: 'Test Unit for .net application'

on:
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x', '6.0.x']
    continue-on-error: ${{ matrix.dotnet-version == '5.0.x' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0  

      - name: Set up .NET Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}   

      - name: Unit Tests
        run: |
          if find ./  -name "*.sln" ; then
          dotnet test */*.sln  
          else
          dotnet test */*.csproj            
        shell: bash  